[tool.black]
line-length = 100
include = "\\.py$"
target-version = ["py311"]

[tool.ruff]
line-length = 100
exclude = [
  "apps/frontend",
  "node_modules",
  "scripts",
]
select = ["E", "F", "I", "B"]
ignore = ["B008"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
strict_optional = true
