apiVersion: apps/v1
kind: Deployment
metadata:
  name: glocal-frontend
  labels:
    app: glocal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glocal-frontend
  template:
    metadata:
      labels:
        app: glocal-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/example/glocal-frontend:latest
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.glocal.local"
            - name: NEXT_PUBLIC_MINIO_PUBLIC_URL
              value: "https://minio.glocal.local"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: glocal-frontend
spec:
  selector:
    app: glocal-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
