[build-system]
requires = ["setuptools>=62", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "glocal-service-kit"
version = "0.1.0"
description = "Utilities shared across Glocal Ads AI services"
authors = [{name = "GloCal"}]
requires-python = ">=3.11"
dependencies = [
    "aio-pika>=9.4.1",
    "boto3>=1.34.23",
    "asyncpg>=0.29.0",
    "redis>=5.0.1",
    "sqlalchemy>=2.0.25",
    "pydantic>=2.5.0",
]

[tool.setuptools.packages.find]
where = ["src"]
