name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r apps/api/requirements.txt
          pip install -r apps/api/requirements-dev.txt
          for req in services/*/requirements.txt; do pip install -r "$req"; done
      - name: Ruff
        run: ruff check apps/api services packages
      - name: Black
        run: black --check apps/api services packages
      - name: Mypy
        run: mypy apps/api/app

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
